# Generated by Django 5.0.14 on 2026-03-31 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код ISO')),
                ('name', models.CharField(max_length=10, verbose_name='Назва')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='Відстежується')),
                ('current_rate_buy', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Поточна купівля')),
                ('current_rate_sell', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Поточний продаж')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_buy', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс купівлі')),
                ('rate_sell', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс продажу')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час запису')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='currencies.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Історія',
                'verbose_name_plural': 'Історії',
                'ordering': ['-timestamp'],
            },
        ),
    ]
